#!/bin/bash

set -euo pipefail

git checkout gh-pages
git merge master --no-edit

./build_book

cd slides
./build-all
cd ../

git add .
git commit -m "Update pages"
git push

rm -r ./book
rm ./slides/*.html

git checkout master
