#!/bin/bash

set -euo pipefail

yarn install
for SLIDE in intro js_ecosystem react_intro react_2 reducers asynchronous_actions bidirectional routes_and_optimizations react_visual_testing outro
do
  echo "Building $SLIDE"
  ./node_modules/.bin/remarker build -s $SLIDE.md
  rm -f $SLIDE.html
  mv ./build/index.html $SLIDE.html
done
